[.heuristics, background-color="#616161"]
== Nielsen usability heuristics

// https://www.nngroup.com/articles/ten-usability-heuristics/
// https://docs.google.com/document/d/1iB21XPG1pl1sxGdq2zskjeZnx7Ezs1VX1ImWBPJsJZ4/edit

*Jakob Nielsen's 10 general principles for interaction design (published 1990).*

They are called "heuristics" because they are broad rules of thumb and not specific usability guidelines.



[.heuristics, background-color="#616161"]
== Visibility of system status

The system should always keep users informed about what is going on, through appropriate feedback within reasonable time.

[.heuristics.fail, background-color="#616161"]
== Visibility of system status

The system should always keep users informed about what is going on, through appropriate feedback within reasonable time.

[NOTE.speaker]
====
Important, but not relevant from our (code) perspective
====


[.heuristics, background-color="#616161"]
==  System and the real world match

The system should speak the users' language, with words, phrases and concepts familiar to the user, rather than system-oriented terms. Follow real-world conventions, making information appear in a natural and logical order.

[.heuristics.ok, background-color="#616161"]
==  System and the real world match

The system should speak the users' language, with words, phrases and concepts familiar to the user, rather than system-oriented terms. Follow real-world conventions, making information appear in a natural and logical order.

[NOTE.speaker]
====
* As with `regionaMatches`
** User's context is around length, offsets not boolean, int, int
====



[.heuristics, background-color="#616161"]
== User control and freedom

Users often choose system functions by mistake and will need a clearly marked "emergency exit" to leave the unwanted state without having to go through an extended dialogue. Support undo and redo.


[.heuristics.fail, background-color="#616161"]
== User control and freedom

Users often choose system functions by mistake and will need a clearly marked "emergency exit" to leave the unwanted state without having to go through an extended dialogue. Support undo and redo.

[NOTE.speaker]
====
In programming we have this kind of for granted!
====


[.heuristics, background-color="#616161"]
== Consistency and standards

Users should not have to wonder whether different words, situations, or actions mean the same thing. Follow platform conventions.

[.heuristics.ok, background-color="#616161"]
== Consistency and standards

Users should not have to wonder whether different words, situations, or actions mean the same thing. Follow platform conventions.

[NOTE.speaker]
====
Obvious - you've seen it with `Observable` and `Collections` example
====


[.heuristics, background-color="#616161"]
== Error prevention

Even better than good error messages is a careful design which prevents a problem from occurring in the first place. Either eliminate error-prone conditions or check for them and present users with a confirmation option before they commit to the action.

[.heuristics.ok, background-color="#616161"]
== Error prevention

Even better than good error messages is a careful design which prevents a problem from occurring in the first place. Either eliminate error-prone conditions or check for them and present users with a confirmation option before they commit to the action.

[NOTE.speaker]
====
* That's why I value compiler and it's support with types.
* Also tests and assertion explanations; see JUnit vs. Hamcrest vs. Spock
====


[.heuristics, background-color="#616161"]
== Recognition rather than recall

Minimize the user's memory load by making objects, actions, and options visible. The user should not have to remember information from one part of the dialogue to another. Instructions for use of the system should be visible or easily retrievable whenever appropriate.

[.heuristics.ok, background-color="#616161"]
== Recognition rather than recall

Minimize the user's memory load by making objects, actions, and options visible. The user should not have to remember information from one part of the dialogue to another. Instructions for use of the system should be visible or easily retrievable whenever appropriate.

[NOTE.speaker]
====
Remeber builder pattern?
====


[.heuristics, background-color="#616161"]
== Flexibility and efficiency of use

Accelerators -- unseen by the novice user -- may often speed up the interaction for the expert user such that the system can cater to both inexperienced and experienced users. Allow users to tailor frequent actions.

[.heuristics.ok, background-color="#616161"]
== Flexibility and efficiency of use

Accelerators -- unseen by the novice user -- may often speed up the interaction for the expert user such that the system can cater to both inexperienced and experienced users. Allow users to tailor frequent actions.

[NOTE.speaker]
====
We can use builder pattern - but we don't need to.
====


[.heuristics, background-color="#616161"]
== Aesthetic and minimalist design

Dialogues should not contain information which is irrelevant or rarely needed. Every extra unit of information in a dialogue competes with the relevant units of information and diminishes their relative visibility.

[.heuristics.ok, background-color="#616161"]
== Aesthetic and minimalist design

Dialogues should not contain information which is irrelevant or rarely needed. Every extra unit of information in a dialogue competes with the relevant units of information and diminishes their relative visibility.

[.heuristics, background-color="#616161"]
== Errors recovery

*Help users recognize, diagnose, and recover from errors*

Error messages should be expressed in plain language (no codes), precisely indicate the problem, and constructively suggest a solution.

[.heuristics.fail, background-color="#616161"]
== Errors recovery

*Help users recognize, diagnose, and recover from errors*

Error messages should be expressed in plain language (no codes), precisely indicate the problem, and constructively suggest a solution.

[.heuristics, background-color="#616161"]
== Help and documentation

Even though it is better if the system can be used without documentation, it may be necessary to provide help and documentation. Any such information should be easy to search, focused on the user's task, list concrete steps to be carried out, and not be too large.

[.heuristics.fail, background-color="#616161"]
== Help and documentation

Even though it is better if the system can be used without documentation, it may be necessary to provide help and documentation. Any such information should be easy to search, focused on the user's task, list concrete steps to be carried out, and not be too large.

// TODO: można się zastanowić o rozszerzenie tej listy o "wyraziste błedy przykrywają małe błędy"
